### ISSUE TITLE
Hidrology Model #MEGADAPT

### ISSUE THREAD

**Issue by marcoajh** [sostenibilidad-unam/layers#37]
@kwhitney727 
According to what we talked about in last Monday's videoconference, I reproduced steps III and VI of Appendix B to calculate the number of curve for each elevation band in each subwatershed and we can already calculate the CN for each step of time.
Also, following the instructions in the "ModelMethods. pdf" file, I calculated the Sm parameter (maximum capacity). 

In step II of the "ModelMethods. pdf" file the suggested steps are:
i Calculate the maximum capacity first.
ii Load all metorological timeseries.
iii Load SWMT.csv.
With section i there is no problem, it is already done, but with sections ii and iii, where or with what program should they be loaded? Is there an Excel spreadsheet where this calculation can be done?

Can the forcings data be spatially used? how?

**Comment by kwhitney727** [comment]
The steps in Model Methods are suggested for you to develop in whichever programlanguage you choose to run the model (e.g. python, netlogo, matlab, etc). In this model program, you would redo steps i, ii, and iii for each timestep. Step i uses equation 2. steps ii and iii would acess your meteorological timeseries and then your master subwatershed table. There is no program or Excel spreadsheet that already does this. It needs to be programmed within your daily loop of the model.

**Comment by marcoajh** [comment]
We're working on that, thank you.
