### ISSUE TITLE
Proporcionar capas geográficas al equipo de salud #megadapt

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/layers#69]
@aleestrada @yosunemiquela @nallelyvs 
ubicación de los datos: \MEGADAPT\mega_sig\gis_compartido
La liga se compartirá mediante correo para que puedan descargar los archivos

- [x]  1. Capa de incidencia de enfermedades diarréicas por AGEBs de la Secretaría de Salud de 2007-2014.

- [x]  2. Censo de población de INEGI por AGEB de los años 2005-2010.

- [x]  3. Capa de comercios informales de alimentos.

- [x]  4. Capa del sistema de drenaje.

- [x]  5. Capa de índice de severidad de encharcamientos de SACMEX de los años 2007 a 2014 que procesó Yosune; si se puede por separado bien, sino los datos acumulados.

- [x]  6. Datos de causas de encharcamientos de los años 2007 a 2014 (no importa que venga por colonia).

**Comment by edithvilla** [comment]
@aleestrada @yosunemiquela @nallelyvs  ya está la capa geográfica del sistema de drenaje:
DrenProf_sacmex.shp, con sus respectivos metadatos

**Comment by aleestrada** [comment]
Se agregó a la carpeta la capa con la incidencia de enfermedades gastrointestinales por patógeno: salud_patogeno.shp, con sus metadatos.

**Comment by aleestrada** [comment]
Se agregó a la carpeta la capa con el número de puestos de comida por AGEB: puestos_comida.shp, con sus metadatos.
